### PR TITLE
Add config option to disable log coloration

### PR DESCRIPTION
**Pull request by memory**
Color logs are great in person, but not so awesome when you're trying
to view them in a log aggregation services e.g. splunk, stackdriver,
ELK, etc.

### CODE REVIEW

**Comment by mxschmitt** [comment]
Hi,
i think, the error will be thrown, because no `data` directory will be created for this "unit test". I will dig into this issue maybe later.

**Comment by memory** [comment]
Oh, I see the problem -- the test isn't calling ReadInConfig() any more, and it wasn't failing for me locally because the test makes a local `data` directory and doesn't reap it at the end.  Hang on for an update.

**Comment by memory** [comment]
^^^ forces the use of a tempdir for data when running the tests.  If there's a cleaner way to accomplish that I'm all ears.

**Comment by mxschmitt** [comment]
@memory I like your work. If you want, I could add you as collaborator, so your changes could go straight into the code base.

**Comment by memory** [comment]
That'd be awesome, although I do appreciate getting code reviews -- go is not yet my native tongue. :)

**Pull request merged**
